### ISSUE TITLE
i got those errors and i dont know how to slove those

### ISSUE THREAD

**Issue by fankcoder** [onflow/nft-storefront#12]
error: mismatched types
  --> 4be6dc812c12feea768bfe16c16fc28527a69b25e00b15489b7a16faa82998c9:39:22
   |
39 |             receiver: self.flowReceiver,
   |                       ^^^^^^^^^^^^^^^^^ expected `Capability<&AnyResource{FungibleToken.Receiver}>`, got `Capability<&FlowToken.Vault{FungibleToken.Receiver}>`

error: mismatched types
  --> 4be6dc812c12feea768bfe16c16fc28527a69b25e00b15489b7a16faa82998c9:44:35
   |
44 |             nftProviderCapability: self.herosCollection,
   |                                    ^^^^^^^^^^^^^^^^^^^^ expected `Capability<&AnyResource{NonFungibleToken.Provider, NonFungibleToken.CollectionPublic}>`, got `Capability<&IdleMysitcHeros.Collection{NonFungibleToken.Provider, IdleMysitcHeros.HerosCollectionPublic}>`

**Comment by rheaplex** [comment]
Heya.

Where is this from? Is this the tests or your own code? Can you provide a more complete log?

Thank you. 🙂

**Comment by fankcoder** [comment]
i change fungible token address without my deploy on testnet  then it works
https://docs.onflow.org/core-contracts/fungible-token/
