### ISSUE TITLE
Rename `SaleOffer` to `Listing`

### ISSUE THREAD

**Issue by psiemens** [onflow/nft-storefront#15]
The "sale offer" terminology still trips me up -- it feels backwards. I always read it as "this is an offer to buy an item" rather than "this is an offer to sell".

What if we just called them "listings"? You can create a listing, remove a listing, or buy a listing.

Later, if we implement buyer offers or bidding, there is less confusion about who is making the offer. To me, it makes much more sense to say "a buyer is making an offer on a listing".

**Comment by rheaplex** [comment]
The terminology that we used was: you offer an item for sale, and someone accepts that offer.

I didn't realise the ambiguity, but I totally see what you are saying.

The following items will be renamed:
```
SaleOfferAvailable -> ListingAvailable
SaleOfferCompleted -> ListingCompleted
SaleOfferDetails -> ListingDetails
SaleOfferPublic -> ListingPublic
SaleOffer -> Listing
```

Any functions or variables referring to `SaleOffer` will be changed to refer to `Listing`.

Other names will not be changed, for example a `Listing` will still be "accepted".
