### ISSUE TITLE
ExampleNFT.cdc is missing 

### ISSUE THREAD

**Issue by sovietspy2** [onflow/nft-storefront#25]
In [this](https://github.com/onflow/nft-storefront/blob/main/transactions/sell_item.cdc) file we can see this import 
`import ExampleNFT from "../contracts/ExampleNFT.cdc"` but it's not in this repository.

**Comment by sampullman** [comment]
I think this can be closed, it looks like it was added a couple weeks ago: https://github.com/onflow/nft-storefront/blob/main/contracts/utility/ExampleNFT.cdc
