### ISSUE TITLE
how/where do i deploy this repo to test the marketplace?

### ISSUE THREAD

**Issue by latonet** [onflow/nft-storefront#32]
Hi, how/where do i deploy this repo to test the marketplace? Thanks

(i'm used to ethereum/polygon)

**Comment by albeethekid** [comment]
@latonet this contract is already live on both Mainnet and Testnet:

https://github.com/onflow/nft-storefront#contract-addresses

Feel free to use the Testnet version to test it out. 

Happy to connect and chat about building on Flow in general.

**Comment by javiermanzano** [comment]
@albeethekid I'll be very happy to have a quick chat about how to use it to have some customizations like limited editions or other metadata that we specifically need for our Marketplace

**Comment by albeethekid** [comment]
Sure! Shoot me an email and will work out a time to chat asap! albert.khasky@dapperlabs.com
