### ISSUE TITLE
Storefront contract is not ready for Secure Cadence release

### ISSUE THREAD

**Issue by thelebster** [onflow/nft-storefront#44]
### Issue
When I try to deploy NFTStorefront contract with emulator, I get the error.

```
Error: thrown: "execution error code 1101: [Error Code: 1101] cadence runtime error Execution failed:
error: cannot deploy invalid contract
 --> fd133addfe9de7559bfa6ff69d7c73d0a6e270bb9d5d54570f056d677012cdd2:7:8
  |
7 |         acct.contracts.add(
  |         ^

error: mismatched types
   --> 01cf0e2f2f715450.NFTStorefront:456:24
    |
456 |                 return &self.listings[listingResourceID] as! &Listing{ListingPublic}
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `NFTStorefront.Listing{NFTStorefront.ListingPublic}`, got `NFTStorefront.Listing?`
"
```

### Steps to reproduce
* Install flow cli to version 0.36.0.
* Deploy NFTStorefront contract.

### Possible solution
[Secure Cadence has been released](https://forum.onflow.org/t/breaking-changes-coming-with-secure-cadence-release/3052), need to upgrade the Storefront contract to the latest Secure Cadence Version to make it work properly.

**Comment by joshuahannan** [comment]
This is fixed in #43 which will be merged soon
