### ISSUE TITLE
How do I know what listings i am able to fulfill

### ISSUE THREAD

**Issue by bjartek** [onflow/nft-storefront#50]
As a marketplace owner for v2 storefront, how can i fetch information about what listings i can fulfill or not?

The list of addresses that can fulfill an listing is not exposed and there is not method to check if I am allowed to do so or not.

**Comment by satyamakgec** [comment]
> As a marketplace owner for v2 storefront, how can i fetch information about what listings i can fulfill or not?
> 
> The list of addresses that can fulfill an listing is not exposed and there is not method to check if I am allowed to do so or not.

If I understand correctly what you wanna say here -  Is how does the marketplace know which listing it should facilitate? If yes then during the creation of the listing marketplace can pass an identifier so they can easily filter those listings that they created and show them on their UI and other listings (those are not created from their platform) they can facilitate if they wanna earn sweet commission and keep an eye which listing offering the commission and whether there address is listed init or not. 

Does my interpretation of your question right?

**Comment by bjartek** [comment]
Let say that .find in our NFT detail page want to know what listings we can fulfill or not. From my understanding it is impossible to do this using the listing resource on chain. I can check if the given NFT for the given user has a listing, but there is no way for me to know if I can fulfill it or not, or if I cannot to link to the origin site where it can be fulfilled.

**Comment by bluesign** [comment]
it is not possible, you need to access : 
https://github.com/onflow/nft-storefront/blob/6a3982ebc55d053542c25cdf98780e4450a2bb95/contracts/NFTStorefrontV2.cdc#L261

**Comment by bjartek** [comment]
I think it would be useful if a marketplace wants to use this limitation to create private sales that they should also provide a link to where this sale item can be fulfilled.

**Comment by albeethekid** [comment]
@satyamakgec  to clarify, for listing that make use of  _"an optional list of marketplace 
receiver capabilities. In this case, the commission amount must be transferred to one of the capabilities in the list..."_
We should consider exposing something in the listing event, perhaps a flag, to allow the community to know if, or if not, they are able to capture the commission on a given listing, at a glance (we should avoid having to run a script to check every listing) @bjartek did I capture the issue you raised here? Do you have any thoughts for how we could address this?

**Comment by bluesign** [comment]
@satyamakgec, I think some business logic I am missing. 

- an optional list of marketplace receiver capabilities. 

I don't know if there are any storyboards for StoreFront, but this didn't add up for me, what is the use case here? 

For example bloctoBay on listing will add Viv3 ? Or TopShot marketplace will add bloctobay there?

**Comment by bluesign** [comment]
Yeah this is very tricky, marketplaces would like to keep their inventory. ( or they die ) 

Not sure if any sane marketplace would like to share.

**Comment by albeethekid** [comment]
Marketplaces could make use of saleCuts to ensure they are paid. It seems to me that the reason to use the marketplacesCapabilitiy is in case the commission is abused. The idea initially was that Dapps, not marketplaces, would use the commission as a way to entice marketplaces to list an item for sale. And in that case, it might make sense to limit the ability of capturing a commission to a list of known marketplaces.
