### ISSUE TITLE
Improvement - Reduce Gas usage for non-existent NFT in capability

### ISSUE THREAD

**Issue by MaxStalker** [onflow/nft-storefront#6]
@rheaplex @dete I think we can move this code at line 219:
https://github.com/onflow/nft-storefront/blob/e3d22c860df9baa604da4fe22ba0dbaf184de901/contracts/NFTStorefront.cdc#L219-L228

somewhere to line 200, before precessing saleCuts. This shall reduce gas usage for "bad" cases, when NFT at provided capability can't be borrowed and transaction need to be reverted.

One cases, when this could happen - if two users are accepting the offer "at the same time".

**Comment by psiemens** [comment]
Closed by #7
